### ISSUE TITLE
No module named gsm

### ISSUE THREAD

**Issue by thisisnotamerica** [iamckn/airprobe#4]
Hi! Thanks for you work.
result of ```make``` is
```
g++: error: ./gsm.cc: No such file or directory
g++: fatal error: no input files

```
And then result of go.sh is :
```
Traceback (most recent call last):
  File "./gsm_receive.py", line 11, in <module>
    import gsm
ImportError: No module named gsm
```

**Comment by iamckn** [comment]
This is related to #3

**Comment by ghost** [comment]
HELP!

I constantly get this error, put on a clean operating system, libosmocore last version
Ubuntu 16.04 64bit
gnuradio 3.7.9

~ / data / airprobe / gsm-receiver $ make
............................................
/ bin / rm -f .deps / gsm.Std;
.deps / gsm.Sd .deps / gsm.Std;
fi
else
/ bin / rm -f .deps / gsm.S *; exit 1;
fi
**swig error: Unrecognized option -pthread**
Use 'swig -help' for available options.
Makefile: 1217: recipe for target '.deps / gsm-generate-stamp' failed
make [5]: *** [.deps / gsm-generate-stamp] Error 1
make [5]: Leaving directory '/ home / vic / data / airprobe / gsm-receiver / src / lib'
/ bin / bash ../../libtool --tag = CXX --mode = compile g ++ -DHAVE_CONFIG_H -I. -I ../ .. -I -I -I / usr / include -I / usr / include / gnuradio / swig -pthread -I / usr / local / include / -I ../../ src / lib / decoder / openbtsstuff -I / usr / include / python2.7 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps / _gsm_la-gsm.Tpo -c -o _gsm_la-gsm.lo test -f 'gsm.cc' || echo './'gsm.cc
libtool: compile: g ++ -DHAVE_CONFIG_H -I. -I ../ .. -I -I -I / usr / include -I / usr / include / gnuradio / swig -pthread -I / usr / local / include / -I ../../ src / lib / decoder / openbtsstuff -I / usr / include / python2.7 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps / _gsm_la-gsm.Tpo -c ./gsm.cc -fPIC -DPIC -o .libs / _gsm_la-gsm.o
g ++: error: ./gsm.cc: No such file or directory
g ++: fatal error: no input files
compilation terminated.

after the command make -p "CC = gcc-9" I check go.sh
And then result of go.sh is:

Traceback (most recent call last):
File "./gsm_receive.py", line 11, in
import gsm
ImportError: No module named gsm
